# Generated by Django 5.2.7 on 2025-10-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_auth_provider_customuser_google_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="microsoft_id",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
