# Generated by Django 5.2.7 on 2025-10-08 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True, related_name="dependents", to="tasks.task"
            ),
        ),
    ]
