# Generated by Django 5.2.7 on 2025-10-08 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_dependencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="duration",
            field=models.IntegerField(default=1, help_text="Duration in days"),
        ),
        migrations.AddField(
            model_name="task",
            name="parent_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtasks",
                to="tasks.task",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress",
            field=models.IntegerField(
                default=0, help_text="Progress percentage (0-100)"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="SubTask",
        ),
    ]
