# Generated by Django 5.2.7 on 2025-10-14 07:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0001_initial"),
        ("tasks", "0005_task_project"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="task",
            options={"ordering": ["id"]},
        ),
        migrations.AddField(
            model_name="task",
            name="early_finish_day",
            field=models.IntegerField(
                default=0, help_text="Early finish day from project start"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="early_start_day",
            field=models.IntegerField(
                default=0, help_text="Early start day from project start"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="is_critical",
            field=models.BooleanField(
                default=False, help_text="Is this task on the critical path"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="late_finish_day",
            field=models.IntegerField(
                default=0, help_text="Late finish day from project start"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="late_start_day",
            field=models.IntegerField(
                default=0, help_text="Late start day from project start"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="total_float",
            field=models.IntegerField(default=0, help_text="Total float/slack in days"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_critical", "project"], name="tasks_task_is_crit_a15f01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["total_float", "project"], name="tasks_task_total_f_6c7dd7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["early_start_day", "early_finish_day"],
                name="tasks_task_early_s_6efadc_idx",
            ),
        ),
    ]
